version: "3.8"
services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_ROOT_PASSWORD: fella
    ports:
      - 3307:3306
    networks:
      - clinic
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - clinic
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    networks:
      - clinic
    depends_on:
      - mysqldb
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    volumes:
      - ./client:/client
    ports:
      - "5000:5000"
    networks:
      - clinic
    depends_on:
      - api
volumes:
  db:
networks:
  clinic:
    driver: bridge
