version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3307:3306
    networks:
      - clinic
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - clinic
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    networks:
      - clinic
    depends_on:
      - mysqldb
      - redis
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - clinic
    depends_on:
      - api
networks:
  clinic:
    driver: bridge
