version: "3"
services:
  clinic-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - clinic-app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - clinic-app
    depends_on:
      - clinic-api
networks:
  clinic-app:
    driver: bridge
